"""State management helpers for Govee Ultimate devices."""

from custom_components.govee_ultimate import _ensure_event_loop as _ensure_loop

from .device_state import DeviceOpState, DeviceState, ParseOption
from .states import (
    ActiveState,
    BatteryLevelState,
    BiologicalPresenceState,
    BrightnessState,
    ColorRGBState,
    ConnectedState,
    ControlLockState,
    ColorTemperatureState,
    AirQualityHumidityState,
    AirQualityPM25State,
    AirQualityTemperatureState,
    DetectionSettingsState,
    DisplayScheduleState,
    DiyModeState,
    EnablePresenceState,
    LightEffectState,
    HumidityState,
    MMWavePresenceState,
    MicModeState,
    ModeState,
    NightLightState,
    SceneModeState,
    SegmentColorState,
    TimerState,
    TemperatureState,
    IceMakerBasketFullState,
    IceMakerMakingIceState,
    IceMakerNuggetSizeState,
    IceMakerScheduledStartState,
    IceMakerStatusState,
    IceMakerTemperatureState,
    IceMakerWaterEmptyState,
    FilterLifeState,
    FilterExpiredState,
    WaterShortageState,
    PowerState,
    UnknownState,
)

__all__ = [
    "DeviceState",
    "DeviceOpState",
    "ParseOption",
    "PowerState",
    "ModeState",
    "ActiveState",
    "BrightnessState",
    "ColorRGBState",
    "ConnectedState",
    "ControlLockState",
    "ColorTemperatureState",
    "AirQualityTemperatureState",
    "AirQualityHumidityState",
    "AirQualityPM25State",
    "BatteryLevelState",
    "MMWavePresenceState",
    "BiologicalPresenceState",
    "EnablePresenceState",
    "DetectionSettingsState",
    "DisplayScheduleState",
    "NightLightState",
    "HumidityState",
    "SegmentColorState",
    "LightEffectState",
    "MicModeState",
    "DiyModeState",
    "SceneModeState",
    "TimerState",
    "TemperatureState",
    "IceMakerNuggetSizeState",
    "IceMakerBasketFullState",
    "IceMakerWaterEmptyState",
    "IceMakerStatusState",
    "IceMakerScheduledStartState",
    "IceMakerMakingIceState",
    "IceMakerTemperatureState",
    "FilterLifeState",
    "FilterExpiredState",
    "WaterShortageState",
    "UnknownState",
]

_ensure_loop()
